#
# Chef Server Config File
#
# Dynamically generated by Chef - local modifications will be replaced
#


log_level          :info
log_location       STDOUT
file_store_path    "/var/chef/file_store"
file_cache_path    "/var/chef/cache"
ssl_verify_mode    :verify_none
registration_url   "http://127.0.0.1:4000"
openid_url         "http://127.0.0.1:4001"
template_url       "http://127.0.0.1:4000"
remotefile_url     "http://127.0.0.1:4000"
search_url         "http://127.0.0.1:4000"
cookbook_path      [ "/var/chef/site-cookbooks", "/var/chef/cookbooks" ]
node_path          "/var/chef/nodes"
openid_store_path  "/var/chef/openid/store"
openid_cstore_path "/var/chef/openid/cstore"
merb_log_path      "/var/log/chef-server.log"
search_index_path  "/var/chef/search_index"

Chef::Log::Formatter.show_time = false
