#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.

is_smartos()
{
  uname -v | grep "^joyent" 2>&1 >/dev/null
}

if is_smartos; then
    PREFIX="/opt/local"
else
    PREFIX="/usr"
fi

# Clean up binary symlinks if they exist
# see: http://tickets.opscode.com/browse/CHEF-3022
if [ ! -f /etc/redhat-release -o "x$1" = "x0" ]; then
  rm -f $PREFIX/bin/chef-init
  rm -f $PREFIX/bin/chef-client
  rm -f $PREFIX/bin/chef-solo
  rm -f $PREFIX/bin/chef-apply
  rm -f $PREFIX/bin/chef-shell
  rm -f $PREFIX/bin/shef
  rm -f $PREFIX/bin/knife
  rm -f $PREFIX/bin/ohai
fi
