#!/bin/bash
# Startup script for chef-indexer.
#
# chkconfig: - 75 25
# description: Server component of the Chef systems integration framework.
# processname: chef-indexer
#
# pidfile: /var/run/chef/chef-indexer.pid

# Source function library
. /etc/init.d/functions

prog="chef-indexer"
pidfile=/var/run/chef/indexer.pid
lockfile=/var/lock/subsys/$prog
config=/etc/chef/indexer.rb
user="root"
group="root"

start() {
    echo -n "Starting $prog:"
    daemon chef-indexer -d -c "$config" -u "$user" -g "$group" -L /var/log/chef/indexer.log "&>/dev/null"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch ${lockfile}
    return $RETVAL
}

stop() {
    echo -n "Stopping $prog: "
    if [ -f $pidfile ]; then
        killproc chef-indexer
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            failure;
        fi;
    else
        RETVAL=1
        failure;
    fi
    rm -f $lockfile
    echo
    return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  condrestart)
        if [ -f $lockfile ]; then
            stop
            start
        fi
        ;;
  status)
        status chef-indexer
        ;;
  *)
    echo "Usage: $0 {start|stop|restart|condrestart|status}"
    exit 1
esac

exit $RETVAL

