#!/bin/bash
# Startup script for chef-server-webui
#
# chkconfig: - 66 34
# description: Server component of the Chef systems integration framework.
# processname: chef-server-webui
#
# config: /etc/sysconfig/chef-server-webui
# pidfile: /var/run/chef/chef-server-webui.pid

# Source function library
. /etc/init.d/functions

[ -f /etc/sysconfig/chef-server-webui ] && . /etc/sysconfig/chef-server-webui

prog="chef-server-webui"
childpidfiles=${CHILDPIDFILES-/var/run/chef/server-webui.%s.pid}
pidfile=${PIDFILE-/var/run/chef/server-webui.main.pid}
lockfile=${LOCKFILE-/var/lock/subsys/$prog}
config=${CONFIG-/etc/chef/server.rb}
user=${CHEF_USER-chef}
group=${CHEF_GROUP-chef}
cluster_nodes=${CLUSTER_NODES-1}
logfile=${LOGFILE-/var/log/chef/merb-webui.%s.log}
options=${OPTIONS-}

start() {
    echo -n "Starting $prog:"
    daemon $prog -d -c "$cluster_nodes" -C "$config" -u "$user" -G "$group" -L "$logfile" -P "$childpidfiles" "$options" "&>/dev/null"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch ${lockfile}
    return $RETVAL
}

stop() {
    echo -n "Stopping $prog: "
    if [ -f $pidfile ]; then
        killproc $prog
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            failure;
        fi;
    else
        RETVAL=1
        failure;
    fi
    rm -f $lockfile
    echo
    return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  condrestart)
        if [ -f $lockfile ]; then
            stop
            start
        fi
        ;;
  status)
        status $prog
        ;;
  *)
    echo "Usage: $0 {start|stop|restart|condrestart|status}"
    exit 1
esac

exit $RETVAL
