source "https://rubygems.org"

gem "chef-utils", path: File.expand_path("../chef-utils", __dir__) if File.exist?(File.expand_path("../chef-utils", __dir__))

gemspec

group(:development, :test) do
  gem "rake"
  gem "rspec"
end
