require "chef-config/package_task"

ChefConfig::PackageTask.new(File.expand_path("..", __FILE__), "ChefConfig", "chef-config") do |package|
  package.module_path = "chef-config"
end

task :default => :spec

begin
  require "rspec/core/rake_task"
  desc "Run standard specs"
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = FileList["spec/**/*_spec.rb"]
    t.rspec_opts = if ENV["CIRCLECI"]
                     "--profile 10 --format RspecJunitFormatter --out ../test_results/rspec_config.xml"
                   else
                     %w{--profile}
                   end

  end
rescue LoadError
  STDERR.puts "\n*** RSpec not available. (sudo) gem install rspec to run unit tests. ***\n\n"
end
