version: 2
updates:
  - &base
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"

  - &bundler_base
    <<: *base
    package-ecosystem: bundler
    directory: "/"
    target-branch: "main"

  - <<: *bundler_base
    target-branch: "chef-18"

  - <<: *bundler_base
    directory: "/omnibus"
    target-branch: "chef-18"

  - <<: *base
    package-ecosystem: github-actions
    directory: "/"
