version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - "Type: Chore"
    ignore:
      # Due to FIPS builds and having to couple the openssl
      # build itself, we don't let dependabot bump openssl
      - dependency-name: "openssl"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled

  - package-ecosystem: bundler
    directory: "/"
    target-branch: "chef-18"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    labels:
      - "Type: Chore"
    ignore:
        # Due to FIPS builds and having to couple the openssl
        # build itself, we don't let dependabot bump openssl
      - dependency-name: "openssl"
        # chef-18 needs to stay on inspec 5, the pre-license version
      - dependency-name: "inspec-core-bin"
        versions: [">= 6"]
        # chef-18 needs to stay on toml 1 which is less strict
      - dependency-name: "tomlrb"
        versions: [">= 2"]
        # chef-18 is locked to Ruby 3.1, which means we cannot move
        # past pry-byebug 3.11
      - dependency-name: "pry-byebug"
        versions: [">= 3.12.0"]
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled

  - package-ecosystem: bundler
    directory: "/omnibus"
    target-branch: "chef-18"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "chef-18"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "Type: Chore"
    # don't automatically rebase on every single time we're out of date with
    # base (whith is always) because it kills CI capacity
    rebase-strategy: disabled
