documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CODE_OF_CONDUCT.md
          - CONTRIBUTING.md
          - lib/chef/resource/**/*

"Expeditor: Skip All":
  - changed-files:
      - all-globs-to-all-files:
          - "{.expeditor,.buildkite,.github,kitchen-tests,test-kitchen}/**"
          - NOTICE
          - LICENSE
          - dangerfile.js
          - dobi.yaml
