# NOTE: this runs the omnibus cookbook, but doens't mount filesystems or
# run omnibus yet use 'kichen converge' to setup the virt and install
# omnibus cookbooks and then be able to login to it

driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-10.04
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-10.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box
  - name: ubuntu-12.04
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-12.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  - name: ubuntu-12.10
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-12.10
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
  - name: ubuntu-13.04
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-13.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box
  - name: ubuntu-13.10
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-13.10
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
  - name: ubuntu-14.04
    run_list: apt::default
    driver_config:
        box: opscode-ubuntu-14.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: chefdk
    run_list:
      - recipe[omnibus::default]
    attributes:
      omnibus:
        build_user: vagrant
        build_dir:  /home/vagrant/omnibus-chef
        install_dir: /opt/chefdk
  - name: chef
    run_list:
      - recipe[omnibus::default]
    attributes:
      omnibus:
        build_user: vagrant
        build_dir:  /home/vagrant/omnibus-chef
        install_dir: /opt/chef
