AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "spec/data/**/*"
    - "vendor/**/*"
    - "pkg/**/*"
    - "chef-config/pkg/**/*"
    - "habitat/**/*"
Security/Eval:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/ShadowedException:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: true
  Exclude:
    - 'spec/unit/property_spec.rb'
    - 'spec/functional/shell_spec.rb'

# set additional paths
Chef/Ruby/UnlessDefinedRequire:
  Include:
    - 'lib/**/*'
    - 'chef-bin/**/*'
    - 'chef-config/lib/**/*'
    - 'chef-utils/lib/**/*'
