AllCops:
  TargetRubyVersion: 3.1 # this cannot be bumped until we upgrade RuboCop
  Exclude:
    - "spec/data/**/*"
    - "knife/spec/data/**/*"
    - "vendor/**/*"
    - "*/vendor/**/*"
    - "pkg/**/*"
    - "chef-config/pkg/**/*"
    - "habitat/**/*"
Security/Eval:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/InterpolationCheck:
  Enabled: true
  Exclude:
    - 'spec/unit/property_spec.rb'
    - 'spec/functional/shell_spec.rb'
Lint/DeprecatedConstants:
  Enabled: true
  Exclude:
    - lib/chef/node/attribute.rb # false alarms

# Disable these until we upgrade to a modern Rubocop release
Layout/ArgumentAlignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false

# This cop shouldn't alert on the helper / specs itself
Chef/Ruby/LegacyPowershellOutMethods:
  Exclude:
    - 'lib/chef/mixin/powershell_out.rb'
    - 'spec/functional/mixin/powershell_out_spec.rb'
    - 'spec/unit/mixin/powershell_out_spec.rb'

# set additional paths
Chef/Ruby/UnlessDefinedRequire:
  Include:
    - 'lib/**/*'
    - 'chef-bin/**/*'
    - 'chef-config/lib/**/*'
    - 'chef-utils/lib/**/*'
