.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KNIFE\-EXEC" "1" "April 2011" "Chef 0.10.0.beta.7" "Chef Manual"
.
.SH "NAME"
\fBknife\-exec\fR \- Run user scripts using the Chef API DSL
.
.SH "SYNOPSIS"
\fBknife\fR \fBexec\fR \fI(options)\fR
.
.SH "EXEC SUBCOMMAND"

