.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KNIFE\-RECIPE" "1" "April 2011" "Chef 0.10.0.beta.8" "Chef Manual"
.
.SH "NAME"
\fBknife\-recipe\fR \- List the recipes available on a Chef Server
.
.SH "SYNOPSIS"
\fBknife\fR \fBrecipe list [PATTERN]\fR
.
.P
List the recipes available on the server\. The results shown can be limited with the optional PATTERN, which is a regular expression\. PATTERN should be given in quotes, without slashes\.
