#
# NOTE: this runs the omnibus cookbook, but does not actually run Omnibus. Use
# 'kichen converge' to setup the virtual machine and then `kitchen login` to
# SSH into the machine and run Omnibus.
#

driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['..', '/home/vagrant/chef']
    - ['../../omnibus', '/home/vagrant/omnibus']
    - ['../../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  # Always install the latest version of Chef.
  # This is not the version of chef that we're building - this is the version
  # of chef that omnibus needs to build chef/chef.
  require_chef_omnibus: true

platforms:
  - name: centos-5.10
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: centos-7.0
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default
  - name: debian-6.0.8
    run_list: apt::default
  - name: freebsd-9.2
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: freebsd-10.0
    run_list: freebsd::portsnap
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  # The following (private) boxes are shared via Atlas and are only
  # available to users working for Chef. Sorry, it's about software licensing.
  # 
  # Chef-internal users, you will need to:  
  # 1.  Create an Atlas account:  https://atlas.hashicorp.com/
  # 2.  Ping the Release Services room with your Atlas account name
  #     to be added to the relevant team in Atlas,
  # 3.  Do `vagrant login` with your Atlas creds so that you can download
  #     the private boxes.   
  #
  # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # as the default provider by copying `.kitchen.local.yml.vmware.example`
  # over to `.kitchen.local.yml`.
  #
  - name: macosx-10.8
    driver:
      box: chef/macosx-10.8 # private
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: windows-7-professional
    driver:
      box: chef/windows-7-professional # private
  - name: windows-8.1-professional
    driver:
      box: chef/windows-8.1-professional # private
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private
  - name: windows-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private

attribute_defaults: &attribute_defaults
  build_user:          vagrant
  build_user_group:    vagrant
  build_user_password: vagrant

suites:
  - name: angrychef
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/angrychef
    run_list:
      - omnibus::default
  - name: chef
    provisioner:
      chef_omnibus_install_options: -P angrychef
      chef_omnibus_root: /opt/angrychef
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/chef
    run_list:
      - omnibus::default
