source "https://rubygems.org"

gem "rest-client", git: "https://github.com/chef/rest-client", branch: "jfm/ucrt_update1"

gem "omnibus", github: ENV.fetch("OMNIBUS_GITHUB_REPO", "chef/omnibus"), branch: ENV.fetch("OMNIBUS_GITHUB_BRANCH", "main")

gem "omnibus-software", github: ENV.fetch("OMNIBUS_SOFTWARE_GITHUB_REPO", "chef/omnibus-software"), branch: ENV.fetch("OMNIBUS_SOFTWARE_GITHUB_BRANCH", "main")

gem "artifactory"

gem "pedump"

gem "ffi", "<= 1.17.0"

# Pin mixlib-shellout to a version compatible with Ruby 3.0.3 on AIX
# Version 3.4.10+ requires Ruby 3.1+
gem "mixlib-shellout", "~> 3.3.0"

# Pin ffi-yajl to a version compatible with Ruby 3.0.3 on AIX
# Version 2.7.7+ requires Ruby 3.1+
gem "ffi-yajl", "~> 2.6.0"

# Pin train-core to a version compatible with Ruby 3.0.3 on AIX
# Version 3.16.2+ requires Ruby 3.1+
gem "train-core", "~> 3.12.0"

# Pin mixlib-log to a version compatible with Ruby 3.0.3 on AIX
# Version 3.2.3+ requires Ruby 3.1+
gem "mixlib-log", "~> 3.0.0"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle config set --local without development && bundle install` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", ">= 8.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "test-kitchen", ">= 1.23"
  gem "kitchen-vagrant", ">= 1.3.1"
  gem "winrm-fs", "~> 1.0"
end
