name             "audit_test"
maintainer       "The Authors"
maintainer_email "you@example.com"
license          "Apache-2.0"
description      "Installs/Configures audit_test"
long_description "Installs/Configures audit_test"
version          "0.1.0"
