$:.push File.expand_path("../lib", __FILE__)
require "chef-server-api/version"

source :rubygems

gem 'bunny'
gem 'uuidtools'
gem 'ohai'
gem 'dep_selector'

merb_gems_version = "1.1.3"
gem "merb-core", merb_gems_version
gem "merb-assets", merb_gems_version
gem "merb-haml", merb_gems_version
gem "merb-helpers", merb_gems_version
gem "merb-param-protection", merb_gems_version

gem "chef", ChefServerApi::VERSION, :git => "git://github.com/opscode/chef.git", :require => false # load individual parts as needed
gem "chef-solr", ChefServerApi::VERSION, :git => "git://github.com/opscode/chef.git", :require => "chef/solr"

group(:development) do
  gem "thin"
  gem "pry"
end

group(:test) do
  gem "rake"
  gem "rspec", "~> 2.5"
  gem "webrat"
  gem "webrat-rspec-rails"
end

group(:production) do
  gem "unicorn", "~> 2.0.0"
end
