require File.dirname(__FILE__) + '/lib/chef-server-api/version'

require 'rubygems'
require 'rake/gempackagetask'

begin
  require 'merb-core'
  require 'merb-core/tasks/merb'
rescue LoadError
  STDERR.puts "merb is not installed, merb rake tasks will not be available."
end

GEM_NAME = "chef-server-api"

spec = eval(File.read("chef-server-api.gemspec"))

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "Install the gem"
task :install => :package do
  sh %{gem install pkg/#{GEM_NAME}-#{ChefServerApi::VERSION} --no-rdoc --no-ri}
end

desc "Uninstall the gem"
task :uninstall do
  sh %{gem uninstall #{GEM_NAME} -x -v #{ChefServerApi::VERSION} }
end

desc "Create a gemspec file"
task :gemspec do
  File.open("#{GEM_NAME}.gemspec", "w") do |file|
    file.puts spec.to_ruby
  end
end
