Document: chef-integration-test2
Title: Debian chef-integration-test2 Manual
Author: <insert document author here>
Abstract: This manual describes what chef-integration-test2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chef-integration-test2/chef-integration-test2.sgml.gz

Format: postscript
Files: /usr/share/doc/chef-integration-test2/chef-integration-test2.ps.gz

Format: text
Files: /usr/share/doc/chef-integration-test2/chef-integration-test2.text.gz

Format: HTML
Index: /usr/share/doc/chef-integration-test2/html/index.html
Files: /usr/share/doc/chef-integration-test2/html/*.html
