require 'chef/node/attribute_trait/autovivify'
require 'chef/node/attribute_trait/convert_value'
require 'chef/node/attribute_trait/decorator'
require 'chef/node/attribute_trait/deep_merge_cache'
require 'chef/node/attribute_trait/immutable'
require 'chef/node/attribute_trait/method_missing'
require 'chef/node/attribute_trait/path_tracking'
require 'chef/node/attribute_trait/symbol_convert'
