#
# Copyright 2012-2016, Chef Software, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This is the chef client build with FIPS mode enabled.
#
current_file = __FILE__
chef_project_contents = IO.read(File.expand_path("../chef.rb", current_file))
self.instance_eval chef_project_contents

name "chef-fips"
friendly_name "Chef Client with FIPS OpenSSL"

if windows?
  # NOTE: Ruby DevKit fundamentally CANNOT be installed into "Program Files"
  #       Native gems will use gcc which will barf on files with spaces,
  #       which is only fixable if everyone in the world fixes their Makefiles
  install_dir "#{default_root}/opscode/#{name}"
  package_name "chef-fips"
else
  install_dir "#{default_root}/#{name}"
end

# Even if chef marches ahead, make sure that we stay pinned to 1.10.6
# bundler 1.11 introduces some new features that require zlib. The zlib1.dll
# base address is generated by gcc to overlap that of libeay.dll. This will
# force windows into relocating libeay, freaking out the FIPS integrity
# verifier. Lol security indeed.
# Delete this once all dlls we generate are appropriately relocated.
override :bundler, version: "1.10.6"

if windows?
  override :ruby, version: "2.0.0-p645"
else
  override :ruby, version: "2.1.6"
end

override :"rb-readline", version: "v0.5.3"

# Global FIPS override flag.
override :fips, enabled: true

override :chef, version: "local_source"
override :ohai, version: "master"

dependency "rb-readline"

msi_upgrade_code = "819F5DB3-B818-4358-BB2B-54B8171D0A26"
project_location_dir = "chef-fips"

# Use chef's scripts for everything.
resources_path "#{resources_path}/../chef"
