.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHEF\-EXPANDERCTL" "8" "July 2013" "Chef 11.6.0" "Chef Manual"
.
.SH "NAME"
\fBchef\-expanderctl\fR \- management program for chef\-expander
.
.SH "SYNOPSIS"
\fBchef\-expanderctl\fR \fICOMMAND\fR
.
.P
\fBCommands:\fR
.
.TP
\fBhelp\fR
Show help message
.
.TP
\fBqueue\-depth\fR
display the aggregate queue backlog
.
.TP
\fBqueue\-status\fR
show the backlog and consumer count for each vnode queue
.
.TP
\fBnode\-status\fR
show the status of the nodes in the cluster
.
.TP
\fBlog\-level\fR
sets the log level of all nodes in the cluster
.
.SH "DESCRIPTION"
Chef\-expanderctl is a management program that allows you to get status information or change the logging verbosity (without restarting)\. chef\-expanderctl has the following commands:
.
.IP "\(bu" 4
\fBchef\-expanderctl help\fR prints usage\.
.
.IP "\(bu" 4
\fBchef\-expanderctl queue\-depth\fR Shows the total number of messages in the queues\.
.
.IP "\(bu" 4
\fBchef\-expanderctl queue\-status\fR Show the number of messages in each queue\. This is mainly of use when debugging a Chef Expander cluster\.
.
.IP "\(bu" 4
\fBchef\-expanderctl log\-level LEVEL\fR Sets the log level on a running Chef Expander or cluster\. If you suspect that a worker process is stuck, as long as you are using clustered operation, you can simply kill the worker process and it will be restarted by the master process\.
.
.IP "" 0
.
.SH "SEE ALSO"
\fBchef\-expander\-cluster\fR(8) \fBchef\-solr\fR(8)
.
.P
Full documentation for Chef and chef\-server is located on the Chef wiki, http://wiki\.opscode\.com/display/chef/Home\.
.
.SH "AUTHOR"
Chef was written by Adam Jacob \fIadam@ospcode\.com\fR of Opscode (http://www\.opscode\.com), with contributions from the community\. This manual page was created by Nuo Yan \fInuo@opscode\.com\fR\. Permission is granted to copy, distribute and / or modify this document under the terms of the Apache 2\.0 License\.
.
.P
On Debian systems, the complete text of the Apache 2\.0 License can be found in /usr/share/common\-licenses/Apache\-2\.0\.
