.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHEF\-SOLR" "8" "April 2013" "Chef 11.4.4" "Chef Manual"
.
.SH "NAME"
\fBchef\-solr\fR \- Runs as Chef\'s search server
.
.SH "SYNOPSIS"
\fBchef\-solr\fR \fI(options)\fR
.
.TP
\fB\-c\fR, \fB\-\-config CONFIG\fR
The configuration file to use
.
.TP
\fB\-d\fR, \fB\-\-daemonize\fR
Daemonize the process
.
.TP
\fB\-g\fR, \fB\-\-group GROUP\fR
Group to set privilege to
.
.TP
\fB\-l\fR, \fB\-\-log_level LEVEL\fR
Set the log level (debug, info, warn, error, fatal)
.
.TP
\fB\-L\fR, \fB\-\-logfile LOGLOCATION\fR
Set the log file location, defaults to STDOUT \- recommended for daemonizing
.
.TP
\fB\-P\fR, \fB\-\-pid PIDFILE\fR
Set the PID file location, defaults to /tmp/chef\-solr\.pid
.
.TP
\fB\-D\fR, \fB\-\-solr\-data\-dir PATH\fR
Where the Solr data lives
.
.TP
\fB\-x\fR, \fB\-\-solor\-heap\-size SIZE\fR
Set the size of the Java Heap
.
.TP
\fB\-H\fR, \fB\-\-solr\-home\-dir PATH\fR
Solr home directory
.
.TP
\fB\-j\fR, \fB\-\-java\-opts OPTS\fR
Raw options passed to Java
.
.TP
\fB\-x\fR, \fB\-\-solor\-heap\-size\fR
Set the size of the Java Heap
.
.TP
\fB\-W\fR, \fB\-\-solr\-jetty\-dir PATH\fR
Where to place the Solr Jetty instance
.
.TP
\fB\-u\fR, \fB\-\-user USER\fR
User to set privilege to
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show chef\-solr version
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this message
.
.SH "DESCRIPTION"
Chef\-solr provides search service for Chef\. You need to have both chef\-solr and chef\-expander\-cluster running in order for search to work\.
.
.P
\fBInstallation\fR
.
.P
Make sure you backed up your data if you are upgrading from a previous version\. Run chef\-solr\-installer to upgrade your Chef Solr installation\. Answer "yes" when prompted for confirmation\. The process should look like this:
.
.IP "" 4
.
.nf

yourshell> chef\-solr\-installer
Configuration setting solr_heap_size is unknown and will be ignored

Chef Solr is already installed in /var/chef/solr
Do you want to overwrite the current install? All existing Solr data will be lost\. [y/n] y
Removing the existing Chef Solr installation
  rm \-rf /var/chef/solr
  rm \-rf /var/chef/solr\-jetty
  rm \-rf /var/chef/solr/data
Creating Solr Home Directory
  mkdir \-p /var/chef/solr
  entering /var/chef/solr
  tar zxvf /Users/ddeleo/opscode/chef/chef\-solr/solr/solr\-home\.tar\.gz
Creating Solr Data Directory
  mkdir \-p /var/chef/solr/data
Unpacking Solr Jetty
  mkdir \-p /var/chef/solr\-jetty
  entering /var/chef/solr\-jetty
  tar zxvf /Users/ddeleo/opscode/chef/chef\-solr/solr/solr\-jetty\.tar\.gz

Successfully installed Chef Solr\.
You can restore your search index using `knife index rebuild`
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
\fBchef\-expander\-cluster\fR(8)
.
.P
Full documentation for Chef and chef\-server is located on the Chef wiki, http://wiki\.opscode\.com/display/chef/Home\.
.
.SH "AUTHOR"
Chef was written by Adam Jacob \fIadam@ospcode\.com\fR of Opscode (http://www\.opscode\.com), with contributions from the community\. This manual page was written by Joshua Timberman \fIjoshua@opscode\.com\fR with help2man\. Permission is granted to copy, distribute and / or modify this document under the terms of the Apache 2\.0 License\.
.
.P
On Debian systems, the complete text of the Apache 2\.0 License can be found in /usr/share/common\-licenses/Apache\-2\.0\.
