.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHEF\-CLIENT" "8" "July 2013" "Chef 11.6.0" "Chef Manual"
.
.SH "NAME"
\fBchef\-client\fR \- Runs a client node connecting to a chef\-server\.
.
.SH "SYNOPSIS"
\fBchef\-client\fR \fI(options)\fR
.
.TP
\fB\-S\fR, \fB\-\-server CHEFSERVERURL\fR
The chef server URL
.
.TP
\fB\-c\fR, \fB\-\-config CONFIG\fR
The configuration file to use
.
.TP
\fB\-d\fR, \fB\-\-daemonize\fR
Daemonize the process
.
.TP
\fB\-g\fR, \fB\-\-group GROUP\fR
Group to set privilege to
.
.TP
\fB\-i\fR, \fB\-\-interval SECONDS\fR
Run chef\-client periodically, in seconds
.
.TP
\fB\-j\fR, \fB\-\-json\-attributes JSON_ATTRIBS\fR
Load attributes from a JSON file or URL
.
.TP
\fB\-E\fR, \fB\-\-environment ENVIRONMENT\fR
Set the Chef Environment on the node
.
.TP
\fB\-l\fR, \fB\-\-log_level LEVEL\fR
Set the log level (debug, info, warn, error, fatal)
.
.TP
\fB\-L\fR, \fB\-\-logfile LOGLOCATION\fR
Set the log file location, defaults to STDOUT \- recommended for daemonizing
.
.TP
\fB\-N\fR, \fB\-\-node\-name NODE_NAME\fR
The node name for this client
.
.TP
\fB\-o\fR, \fB\-\-override\-runlist\fR
Replace current run list with specified items
.
.TP
\fB\-K\fR, \fB\-\-validation_key KEY_FILE\fR
Set the validation key file location, used for registering new clients
.
.TP
\fB\-k\fR, \fB\-\-client_key KEY_FILE\fR
Set the client key file location
.
.TP
\fB\-s\fR, \fB\-\-splay SECONDS\fR
The splay time for running at intervals, in seconds
.
.TP
\fB\-u\fR, \fB\-\-user USER\fR
User to set privilege to
.
.TP
\fB\-P\fR, \fB\-\-pid PIDFILE\fR
Set the PID file location, defaults to /tmp/chef\-client\.pid
.
.TP
\fB\-\-once\fR
Cancel any interval or splay options, run chef once and exit
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show chef version
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this message
.
.SH "DESCRIPTION"
The Chef Client is where almost all of the work in Chef is done\. It communicates with the Chef Server via REST, authenticates via Signed Header Authentication, and compiles and executes Cookbooks\.
.
.P
A Chef Client does work on behalf of a Node\. A single Chef Client can run recipes for multiple Nodes\.
.
.P
Clients are where all the action happens \- the Chef Server and Chef Expander are largely services that exist only to provide the Client with information\.
.
.SH "SEE ALSO"
Full documentation for Chef and chef\-client is located on the Chef wiki, http://wiki\.opscode\.com/display/chef/Home\.
.
.SH "AUTHOR"
Chef was written by Adam Jacob \fIadam@ospcode\.com\fR of Opscode (http://www\.opscode\.com), with contributions from the community\. This manual page was written by Joshua Timberman \fIjoshua@opscode\.com\fR with help2man\. Permission is granted to copy, distribute and / or modify this document under the terms of the Apache 2\.0 License\.
.
.P
On Debian systems, the complete text of the Apache 2\.0 License can be found in /usr/share/common\-licenses/Apache\-2\.0\.
