name             'git-cookbook'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures example'
long_description 'Installs/Configures example'
version          '0.1.0'
