source :rubygems
source 'http://gems.github.com'
source 'http://gems.rubyforge.org'

gemspec
gem 'gruff', '0.3.6'
gem 'thin', '1.2.11'
gem 'rack'
gem 'jscruggs-metric_fu', '1.1.5'
gem 'reek', '1.2.8'
gem 'sdoc'
gem 'roodi', '2.1.0'
gem 'bunny'
gem 'uuidtools'
gem 'ohai'
gem 'dep_selector'
gem 'rmagick'

merb_gems_version = "1.1.3"
gem "merb-core", merb_gems_version
gem "merb-assets", merb_gems_version
gem "merb-haml", merb_gems_version
gem "merb-helpers", merb_gems_version
gem "merb-param-protection", merb_gems_version

gem 'chef', :path => '../chef'
gem 'chef-solr', :path => '../chef-solr'
gem 'chef-server-webui', :path => '../chef-server-webui'
gem 'chef-server-api', :path => '../chef-server-api'
gem 'chef-expander', :path => '../chef-expander'

group :test do
  gem "rake"
  gem "rspec", "~> 2.5"
  gem "webrat"
  gem "webrat-rspec-rails"
end

