source 'https://rubygems.org'

gem "mixlib-install", github: "chef/mixlib-install"
gem "chef-acceptance", github: "chef/chef-acceptance"
gem "test-kitchen", github: "sersut/test-kitchen", branch: "sersut/mixlib-install-update"
gem 'kitchen-inspec'

group(:development) do
  gem "kitchen-vagrant"
  gem "windows_chef_zero"
  gem "winrm-transport"
end
