source 'https://rubygems.org'

gem 'chef-acceptance', github: 'chef/chef-acceptance'
gem 'berkshelf'
gem 'test-kitchen', '~> 1.4.0'
gem 'kitchen-appbundle-updater', '~> 0.0.1'
gem "kitchen-vagrant", '~> 0.17.0'
gem 'kitchen-ec2', github: 'test-kitchen/kitchen-ec2'
gem 'vagrant-wrapper'
