.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KNIFE\-NODE" "8" "April 2011" "Chef 0.10.0.beta.7" "Chef Manual"
.
.SH "NAME"
\fBknife\-node\fR \- Chef Server REST API utility
.
.SH "SYNOPSIS"
\fBknife\fR \fBnode\fR \fIsub\-command\fR \fI(options)\fR
.
.SH "NODE SUB\-COMMANDS"
Nodes are the entities which are configured with Chef\. Typically these are servers or workstations\. Nodes are registered as a client, by default by the fully qualified domain name (fqdn)\. A single client may configure more than one node\.
.
.P
\fBnode bulk delete REGEX\fR \fI(options)\fR
.
.P
Delete nodes on the Chef Server based on a regular expression\. The regular expression (\fIREGEX\fR) should be in quotes, not in //\'s\.
.
.P
\fBnode create NODE\fR \fI(options)\fR
.
.P
Create a new node\.
.
.P
\fBnode delete NODE\fR \fI(options)\fR
.
.P
Delete a single node\.
.
.P
\fBnode edit NODE\fR \fI(options)\fR
.
.P
Edit a node\.
.
.P
\fBnode from file FILE\fR \fI(options)\fR
.
.P
Create a node from a JSON file\.
.
.P
\fBnode list\fR \fI(options)\fR
.
.TP
\fB\-w\fR, \fB\-\-with\-uri\fR
Show corresponding URIs
.
.P
List all nodes\.
.
.P
\fBnode run_list add [NODE] [ENTRY]\fR \fI(options)\fR
.
.TP
\fB\-a\fR, \fB\-\-after ITEM\fR
Place the ENTRY in the run list after ITEM
.
.P
Add a recipe or role to the node\'s \fBrun_list\fR\.
.
.P
\fBnode run_list remove [NODE] [ENTRY]\fR \fI(options)\fR
.
.P
Remove a recipe or role from the node\'s \fBrun_list\fR\.
.
.P
\fBnode show NODE\fR \fI(options)\fR
.
.TP
\fB\-a\fR, \fB\-\-attribute [ATTR]\fR
Show only one attribute
.
.TP
\fB\-r\fR, \fB\-\-run\-list\fR
Show only the run list
.
.P
Show a node\.
