suites:
  - name: docker-default
    attributes:
      apt-docker:
        repos:
          docker-main:
            keyserver: hkp://ha.pool.sks-keyservers.net
      docker:
        version: 1.10.0
    run_list:
      - recipe[apt]
      - recipe[chef-apt-docker]
    includes: [ubuntu-14.04]
