
host_project_path = File.expand_path("../../..", __FILE__)
guest_project_path = "/home/vagrant/#{File.basename(host_project_path)}"
project_name = "chef"

Vagrant.configure("2") do |config|
  config.vm.hostname = "#{project_name}-omnibus-build-lab"
  config.vm.box = "dummy"

  config.vm.provider :joyent do |joyent|
    # Joyent login
    joyent.joyent_username = ENV['SDC_CLI_ACCOUNT']
    joyent.joyent_keyname  = ENV['SDC_CLI_KEY_ID']
    joyent.joyent_keyfile  = ENV['SDC_CLI_IDENTITY']
    joyent.joyent_api_url  = ENV['SDC_CLI_URL']

    # sdc:sdc:base64:13.1.0
    joyent.dataset = "9eac5c0c-a941-11e2-a7dc-57a6b041988f"

    joyent.flavor = "Small 1GB"
    joyent.ssh_username = "root"
    joyent.ssh_private_key_path = ENV['SDC_CLI_IDENTITY']
  end

  # Enable the berkshelf-vagrant plugin
  config.berkshelf.enabled = true
  # The path to the Berksfile to use with Vagrant Berkshelf
  config.berkshelf.berksfile_path = File.expand_path("../../../Berksfile", __FILE__)

  config.ssh.max_tries = 40
  config.ssh.timeout   = 120
  config.ssh.forward_agent = true

  config.vm.synced_folder host_project_path, guest_project_path

  # Uncomment for DEV MODE
  # config.vm.synced_folder File.expand_path("../../../../omnibus-ruby", __FILE__), "/home/vagrant/omnibus-ruby"
  # config.vm.synced_folder File.expand_path("../../../../omnibus-software", __FILE__), "/home/vagrant/omnibus-software"

  # bootstrap chef
  config.vm.provision :shell, :inline => <<-INSTALL_CHEF
    getent passwd | grep vagrant
    if [ $? -gt 0 ]; then
      useradd vagrant
    fi

    # ruby
    pkgin list | grep ^ruby193-[0-9]
    if [ $? -gt 0 ]; then
      pkgin -y install ruby193
    fi

    # gmake
    pkgin list | grep ^gmake-[0-9]
    if [ $? -gt 0 ]; then
      pkgin -y install gmake
    fi

    # gcc
    pkgin list | grep ^gcc47-[0-9]
    if [ $? -gt 0 ]; then
      pkgin -y install gcc47
    fi

    # chef
    gem list | grep ^chef
    if [ $? -gt 0 ]; then
      gem install chef --bindir=/opt/local/bin/ --no-ri --no-rdoc
    fi
  INSTALL_CHEF

  # prepare VM to be an Omnibus builder
  config.vm.provision :chef_solo do |chef|
    chef.json = {
      "omnibus" => {
        "build_user" => "root",
        "build_dir" => guest_project_path,
        "install_dir" => "/opt/#{project_name}"
      }
    }

    chef.run_list = [
      "recipe[omnibus::default]"
    ]
  end

  config.vm.provision :shell, :inline => <<-OMNIBUS_BUILD
    sudo mkdir -p /opt/#{project_name}
    export PATH=/opt/local/bin:$PATH
    cd #{guest_project_path}
    bundle install --binstubs
    bin/omnibus build project #{project_name}
  OMNIBUS_BUILD
end
