#!/bin/ksh

function create_chef_txt {
        touch /tmp/chefinittest.txt
}

function delete_chef_txt {
        rm /tmp/chefinittest.txt
}

function rename_chef_txt {
        mv /tmp/chefinittest.txt /tmp/$1
}

case "$1" in
start )
        create_chef_txt
        ;;
stop )
        delete_chef_txt
        ;;
reload )
        rename_chef_txt "chefinittest_reload.txt"
        ;;
restart )
        delete_chef_txt
        create_chef_txt
        rename_chef_txt "chefinittest_restart.txt"
        ;;
* )
        echo "Usage: $0 (start | stop | restart | reload)"
        exit 1
esac
