#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
# Build you some jenkins
#

set -e
set -x

os=`uname -s`

# Return truthy (which is zero) if a command does not exist
# (this is deliberately inverted because /bin/sh on Solaris does not support "if ! exists" syntax)
not_exists() {
  if command -v $1 >/dev/null 2>&1; then
    return 1
  else
    return 0
  fi
}

exists() {
  if command -v $1 >/dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

if [ "x$os" = "xAIX" ]; then
  # need to unset LIBPATH on AIX (like LD_LIBRARY_PATH on Solaris, Jenkins sets this (wrongly) on AIX)
  unset LIBPATH
fi

if [ -z $OMNIBUS_PROJECT_NAME ]; then
  echo "OMNIBUS_PROJECT_NAME environment variable is not set!"
  exit 1
fi

# create the build timestamp file for fingerprinting if it doesn't exist (manual build execution)
if [ ! -f build_timestamp ]; then
  date > build_timestamp
  echo "$BUILD_TAG / $BUILD_ID" > build_timestamp
fi

mkdir -p jenkins/chef-solo/cache/remote_file

PATH=/opt/ruby1.9/bin:/usr/local/bin:$PATH
export PATH

if not_exists chef-solo; then
  sudo gem install chef --no-ri --no-rdoc
fi

# ensure bundler is installed
if not_exists bundle; then
  sudo gem install bundler --no-ri --no-rdoc
fi

# TEMPORARY: can't install berks on AIX
if [ "x$os" != "xAIX" ]; then
  # ensure berkshelf is installed
  if not_exists berks; then
    sudo gem install berkshelf --no-ri --no-rdoc
  fi

  # install omnibus cookbook and dependencies
  # Disable berks install since we don't need it anymore
  # berks install --path=vendor/cookbooks

  if [ -f "/etc/release" ] && [ -n "`cat /etc/release | grep -i solaris`" ]; then
    dna=`pwd`/jenkins/dna-solaris2.json
  else
    dna=`pwd`/jenkins/dna.json
  fi
  # Omnibus build server prep tasks, including build ruby
  # TEMPORARY: Temporarily disable chef-solo runs.
  # Can be reverted when https://github.com/opscode-cookbooks/omnibus/pull/12
  # is merged and released.
  # Note that currently this functionality is not needed since we are far away
  # from rebuilding slaves using cookbooks in ci.opscode.us.
  # sudo -i env PATH=$PATH chef-solo -c `pwd`/jenkins/solo.rb -j $dna -l debug
  # END of temporary change.
  # Fix root-owned perms left over from running chef-solo (cache turds, etc)
  set +e
  sudo chown -R jenkins-node `pwd` || sudo chown -R jenkins `pwd`
  set -e
fi

if [ "x$os" = "xAIX" ]; then
  # AIX is hateful and requires a bunch of root stuff to build BFF packages
  sudo rm -rf /.info || true
  sudo mkdir /.info || true
  sudo chown jenkins /.info || true
  sudo rm -rf /tmp/bff || true
  # deinstall the bff if it got installed, can't build if it is installed
  sudo installp -u $OMNIBUS_PROJECT_NAME || true
  # AIX needs /opt/freeware/bin and /usr/sbin
  if [ -d "/opt/freeware/bin" ]; then
    PATH=/opt/freeware/bin:$PATH:/usr/sbin
    export PATH
  fi
fi

if [ "$CLEAN" = "true" ]; then
  sudo rm -rf "/opt/${OMNIBUS_PROJECT_NAME}" || true
  sudo mkdir -p "/opt/${OMNIBUS_PROJECT_NAME}"
  sudo rm -rf /var/cache/omnibus/pkg/* || true
  sudo rm -rf /var/cache/omnibus/src/* || true
  sudo rm -f /var/cache/omnibus/build/*/*.manifest || true
  sudo rm -f pkg/* || true
fi

# always fix up permissions
sudo chown -R jenkins-node "/opt/${OMNIBUS_PROJECT_NAME}" || sudo chown -R jenkins "/opt/${OMNIBUS_PROJECT_NAME}"
sudo chown -R jenkins-node "/var/cache/omnibus" || sudo chown -R jenkins "/var/cache/omnibus"

# Aaand.. new ruby
PATH=/usr/local/bin:$PATH
export PATH

# horrible hack for solaris 9 to get ffi to compile in the bundle
if [ -f "/etc/release" ]; then
  # solaris /bin/sh needs the stupid || true or set -x bombs here
  release=`cat /etc/release | grep 'Solaris 9' || true`
  if [ "x$release" != "x" ]; then
    # magic CONFIGURE_ARGS to get CFLAGS through bundle/gem install
    CONFIGURE_ARGS="--with-cflags='-U__STRICT_ANSI__'"
    export CONFIGURE_ARGS
  fi
fi

# docs do not install on solaris 9
bundle install --without docs

if [ "$RELEASE_BUILD" = "true" ]; then
  bundle exec omnibus build $OMNIBUS_PROJECT_NAME --no-timestamp
else
  bundle exec omnibus build $OMNIBUS_PROJECT_NAME
fi

# Sign the package on some platforms:
if [ "x$os" != "xAIX" ]; then
  if exists rpm; then
    sudo -i `pwd`/jenkins/sign-rpm "foo" `pwd`/pkg/*rpm
  fi
fi

# Dump the build-generated version so the Omnitruck release script uses the
# correct version string format.
echo "`awk -v p=$OMNIBUS_PROJECT_NAME '$1 == p {print $2}' /opt/${OMNIBUS_PROJECT_NAME}/version-manifest.txt`" > pkg/BUILD_VERSION
