#!/bin/bash

# Just clean the symlinks

cleanup_symlinks() {
  binaries="chef-client chef-solo chef-apply chef-shell ohai"
  for binary in $binaries; do
    rm -f $PREFIX/bin/$binary
  done
}

cleanup_symlinks
