#!/bin/bash
#
# Perform necessary chef-server setup steps after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
	exit 1
}

ln -sf /opt/chef-server/bin/chef-server-ctl /usr/bin || error_exit "Cannot link chef-server-ctl in /usr/bin"
  
if [ -e /etc/opscode/chef-server-running.json ]; then
  echo -e "\033[1mYou have upgraded Chef Server!\033[0m"
  echo
  echo "The next step in the upgrade process is to run:"
  echo
  echo -e "\033[1;31msudo chef-server-ctl upgrade\033[0m"
  echo -e "\033[1;31msudo chef-server-ctl reconfigure\033[0m"
else
  echo -e "\033[1mThank you for installing Chef Server!\033[0m"
  echo
  echo "The next step in the install process is to run:"
  echo
  echo -e "\033[1msudo chef-server-ctl reconfigure\033[0m"
fi

exit 0

