require 'chef/provider/file_strategy/content_from_resource'
require 'chef/provider/file_strategy/content_from_cookbook_file'
require 'chef/provider/file_strategy/content_from_remote_file'
require 'chef/provider/file_strategy/content_from_template'
require 'chef/provider/file_strategy/deploy_cp'
require 'chef/provider/file_strategy/deploy_mv'
require 'chef/provider/file_strategy/deploy_mv_with_restorecon'
