#!/usr/bin/env ruby
# Integration test for rest_api_endpoint and rest_identity_property DSL changes.
# Runs against the public REST sandbox at https://api.restful-api.dev/objects
#
# Usage:
#   bundle exec ruby scripts/rest_resource_integration_test.rb

require "rubygems"
require "bundler/setup"

require "chef"
require "train"
require "train-rest"
require "chef/dsl/rest_resource"

# ── Helpers ───────────────────────────────────────────────────────────────────

def pass(msg)  = puts "  ✅ #{msg}"
def fail!(msg) = (puts "  ❌ #{msg}\n"; exit 1)

def section(title)
  puts "\n=== #{title} ==="
end

# ── Resource definition using the new DSL ────────────────────────────────────
#
# Mirrors the pattern shown in the _rest_resource.rb documentation examples.
# rest_identity_property should auto-generate rest_api_document as /objects/{id}.

class Chef
  class Resource
    class RestfulObject < Chef::Resource
      use "core::rest_resource"

      provides :restful_object

      property :id,   String
      property :name, String, name_property: true

      rest_api_endpoint   "https://api.restful-api.dev"
      rest_api_collection "/objects"
      rest_identity_property :id

      rest_property_map({ name: "name" })
    end
  end
end

klass = Chef::Resource::RestfulObject

# ── 1. DSL verification ───────────────────────────────────────────────────────

section "1. DSL verification"

unless klass.rest_api_endpoint == "https://api.restful-api.dev"
  fail!("rest_api_endpoint expected 'https://api.restful-api.dev', got '#{klass.rest_api_endpoint}'")
end
pass("rest_api_endpoint = #{klass.rest_api_endpoint}")

unless klass.rest_api_collection == "/objects"
  fail!("rest_api_collection expected '/objects', got '#{klass.rest_api_collection}'")
end
pass("rest_api_collection = #{klass.rest_api_collection}")

unless klass.rest_identity_property == :id
  fail!("rest_identity_property expected :id, got #{klass.rest_identity_property.inspect}")
end
pass("rest_identity_property = #{klass.rest_identity_property}")

expected_doc = "/objects/{id}"
unless klass.rest_api_document == expected_doc
  fail!("rest_api_document auto-generation failed — expected '#{expected_doc}', got '#{klass.rest_api_document}'")
end
pass("rest_api_document (auto-generated) = #{klass.rest_api_document}")

# ── 2. Train connection ───────────────────────────────────────────────────────
#
# Uses rest_api_endpoint directly to create the connection, exactly as
# api_connection would in a real Chef run when rest_api_endpoint is set.

section "2. Connecting via rest_api_endpoint"

conn = Train.create("rest", { endpoint: klass.rest_api_endpoint }).connection
pass("Connected to #{klass.rest_api_endpoint}")

# ── 3. GET collection ─────────────────────────────────────────────────────────

section "3. GET #{klass.rest_api_collection} (collection)"

response = conn.get(klass.rest_api_collection)
fail!("GET collection failed — HTTP #{response.code}") unless response.code == 200
fail!("Expected array response") unless response.data.is_a?(Array)
fail!("Collection is empty — nothing to test with") if response.data.empty?
pass("Received #{response.data.length} objects (HTTP #{response.code})")

# Pick the first object's id to use in all subsequent document-level tests
object_id   = response.data.first["id"]
object_name = response.data.first["name"]
pass("Using id=#{object_id}, name='#{object_name}'")

# ── 4. Build document URL from rest_api_endpoint + rest_api_document template ──
#
# This is exactly what rest_url_document does at runtime:
#   endpoint  = rest_api_endpoint  → "https://api.restful-api.dev"
#   template  = rest_api_document  → "/objects/{id}"   (auto-generated by rest_identity_property)
#   expanded  = template.expand(id: object_id)
#
# Verify both halves are correct before hitting the network.

section "4. Document URL construction (rest_api_endpoint + rest_identity_property)"

require "addressable/template"
template     = Addressable::Template.new(klass.rest_api_document)
expanded_doc = template.expand(id: object_id).to_s
full_doc_url = "#{klass.rest_api_endpoint}#{expanded_doc}"

fail!("Template did not expand id") unless expanded_doc == "/objects/#{object_id}"
pass("rest_api_document template expanded to #{expanded_doc}")
pass("Full document URL = #{full_doc_url}")

# ── 5. GET individual document via the constructed URL ────────────────────────

section "5. GET #{expanded_doc} (individual document)"

response = conn.get(expanded_doc)
fail!("GET document failed — HTTP #{response.code}") unless response.code == 200
fail!("Response id mismatch — expected #{object_id}, got #{response.data['id']}") unless response.data["id"] == object_id
pass("Retrieved — id=#{response.data['id']}, name='#{response.data['name']}'")
pass("Individual document matches collection entry ✓")

# ── Done ──────────────────────────────────────────────────────────────────────

puts "\n✅  All tests passed!\n\n"
