require 'chef/dsl/recipe'
require 'chef/dsl/platform_introspection'
require 'chef/dsl/data_query'
require 'chef/dsl/include_recipe'
require 'chef/dsl/include_attribute'
require 'chef/dsl/registry_helper'
