source "https://supermarket.chef.io"

cookbook "omnibus"

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'chef-cookbooks/omnibus'

group :integration do
  cookbook "apt"
  cookbook "freebsd"
  cookbook "yum-epel"
end
