---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_zero
#  name: chef_github
#  github_owner: "chef"
#  github_repo: "chef"
#  refname: "master"
  data_path: test/fixtures
  client_rb:
    diff_disabled: true

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  # needs updates for 16.04
  #- name: ubuntu-16.04
  # needs updates for 7.2
  #- name: centos-7.2
  - name: centos-6.7
  # needs fixing for 5.11
  #- name: centos-5.11

suites:
  - name: webapp
    run_list:
      - recipe[base::default]
      - recipe[webapp::default]
    attributes:
