---
driver:
  name: proxy
  host: localhost
  reset_command: "echo hello"
  port: <%= ENV["machine_port"] %>
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>
  chef_version: latest

provisioner:
  name: chef_github
  root_path: /opt/kitchen
  require_chef_omnibus: latest
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
  chef_omnibus_install_options: "-c current"
  github_owner: "chef"
  github_repo: "chef"
  refname: <%= ENV['TRAVIS_COMMIT'] %>
  github_access_token: <%= ENV['KITCHEN_GITHUB_TOKEN'] %>
  data_path: test/fixtures
# disable file provider diffs so we don't overflow travis' line limit
  client_rb:
    diff_disabled: true

verifier:
  name: inspec
  format: progress

platforms:
  - name: ubuntu-14.04  # does it matter?

suites:
  - name: awesome_customers_windows
    run_list:
      - recipe[awesome_customers_windows_wrapper::default]
