---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

provisioner:
  name: chef_github
  github_owner: "chef"
  github_repo: "chef"
  refname: <%= %x(git rev-parse HEAD) %>
  data_path: test/fixtures
  client_rb:
    diff_disabled: true

platforms:
  # upstream community mysql cookbook broken on 10.04
  #- name: ubuntu-10.04
  #  run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  # upstream community mysql cookbook also broken on 14.10
  #- name: ubuntu-14.10
  #  run_list: apt::default
  - name: centos-6.4
    run_list: yum-epel::default
  - name: centos-5.10
    run_list: yum-epel::default

suites:
  - name: webapp
    run_list:
      - recipe[apt::default]
      - recipe[webapp::default]
    attributes:
