---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

verifier:
  name: inspec
  format: progress

provisioner:
  name: chef_github
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
  chef_omnibus_install_options: "-c current"
  github_owner: "chef"
  github_repo: "chef"
  ohai_refname: "master"
  refname: <%= %x(git rev-parse HEAD) %>
  client_rb:
    diff_disabled: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7
  - name: centos-6

suites:
  - name: base
    run_list:
      - recipe[base::default]
  - name: learnchef
    run_list:
      - recipe[lamp::default]
    data_bags_path: data_bags
    includes:
      - ubuntu-14.04
