---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 2048

verifier:
  name: inspec
  format: progress

provisioner:
  name: chef_github
  chef_omnibus_url: "https://omnitruck.chef.io/install.sh"
  chef_omnibus_install_options: "-c current"
  github_owner: "chef"
  github_repo: "chef"
  ohai_refname: "master"
  refname: <%= %x(git rev-parse HEAD) %>
  data_path: test/fixtures
  client_rb:
    diff_disabled: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.2
  - name: centos-6.7
  # needs fixing for 5.11
  # - name: centos-5.11

suites:
  - name: webapp
    run_list:
      - recipe[base::default]
  - name: awesome_customers_ubuntu
    run_list:
      - recipe[awesome_customers_ubuntu_wrapper::default]
  - name: awesome_customers_rhel
    run_list:
      - recipe[awesome_customers_rhel_wrapper::default]
