source "https://supermarket.chef.io"

cookbook "base", path: "cookbooks/base"

cookbook "awesome_customers_ubuntu_wrapper", path: "cookbooks/awesome_customers_ubuntu_wrapper"
cookbook "awesome_customers_ubuntu", github: "learn-chef/awesome_customers_ubuntu"
cookbook "awesome_customers_rhel_wrapper", path: "cookbooks/awesome_customers_rhel_wrapper"
cookbook "awesome_customers_rhel", github: "learn-chef/awesome_customers_rhel"
