source "https://rubygems.org"

gem "rake" # required to build some native extensions
gem "chef", path: ".."
# remove this ohai pin once we ship the 14 gem
gem "ohai", git: "https://github.com/chef/ohai.git", branch: "master"
gem "berkshelf", git: "https://github.com/berkshelf/berkshelf.git", branch: "master"
gem "kitchen-appbundle-updater", git: "https://github.com/chef/kitchen-appbundle-updater", branch: "master"
gem "kitchen-dokken", "< 2.0" # 2.x fails atm: https://travis-ci.org/chef/chef/jobs/199125787
gem "kitchen-inspec", git: "https://github.com/chef/kitchen-inspec.git", branch: "master"
gem "kitchen-vagrant", git: "https://github.com/test-kitchen/kitchen-vagrant.git", branch: "master"
gem "test-kitchen", git: "https://github.com/test-kitchen/test-kitchen.git", branch: "master"
