source "https://rubygems.org"

group :end_to_end do
  gem 'berkshelf'
  gem 'test-kitchen', '~> 1.4.0'
  gem 'kitchen-appbundle-updater', '~> 0.0.1'
  gem "kitchen-vagrant", '~> 0.17.0'
  gem 'kitchen-ec2', github: 'test-kitchen/kitchen-ec2', branch: '40d29858e8ee8ba14492ca54c881d961860b2ae7~1'
end
