source "https://rubygems.org"

gem "knife", path: "."

gem "cheffish", git: "https://github.com/chef/cheffish.git", branch: "main"

group(:development, :test) do # testing only , but why didn't this need to explicit in chef?
  gem "webmock"
  gem "crack", "< 0.4.6" # due to https://github.com/jnunemaker/crack/pull/75
  gem "rake", ">= 12.3.3"
  gem "rspec"
  gem "chef-bin", path: "../chef-bin"
end

group(:omnibus_package, :pry) do
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
end

gem "ohai", git: "https://github.com/chef/ohai.git", branch: "main"
gem "chef", path: ".."
gem "chef-utils", path: File.expand_path("../chef-utils", __dir__) if File.exist?(File.expand_path("../chef-utils", __dir__))
gem "chef-config", path: File.expand_path("../chef-config", __dir__) if File.exist?(File.expand_path("../chef-config", __dir__))
