
gemspec

source "https://rubygems.org"

gem "cheffish", ">= 14" # testing only , but why didn't this need to explicit in chef?
gem "webmock" # testing only
gem "rake"
gem "chef", path: ".."
gem "ohai", git: "https://github.com/chef/ohai.git", branch: "master"
gem "chef-utils", path: File.expand_path("../chef-utils", __dir__) if File.exist?(File.expand_path("../chef-utils", __dir__))
gem "chef-config", path: File.expand_path("../chef-config", __dir__) if File.exist?(File.expand_path("../chef-config", __dir__))
