name             "webapp"
maintainer       ""
maintainer_email ""
license          "Apache-2.0"
description      "Installs/Configures webapp"
long_description "Installs/Configures webapp"
version          "0.1.0"

depends "apache2", "~> 3.2.2"
depends "database", "~> 2.3.1"
depends "mysql", "~> 5.6.3"
depends "php", "~> 1.5.0"
