name             "webapp"
maintainer       ""
maintainer_email ""
license          "Apache-2.0"
description      "Installs/Configures webapp"
long_description "Installs/Configures webapp"
version          "0.1.0"

depends "apache2", "~> 4.0.0"
depends "database", "~> 6.1.1"
depends "php", "~> 4.5.0"
