name             'webapp'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version          '0.1.0'

depends 'apache2'
depends 'database'
depends 'mysql'
depends 'php'
