FROM ubuntu:12.04
ADD chef-container_10.28.2-182-gc7d95c9-1_amd64.deb  /tmp/chef-init.deb
#ADD chef-container_12.14.0.alpha.1-121-g8b3a0f4-0_amd64.deb  /tmp/chef-init.deb
RUN dpkg -i /tmp/chef-init.deb
