.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KNIFE\-STATUS" "1" "April 2013" "Chef 11.4.4" "Chef Manual"
.
.SH "NAME"
\fBknife\-status\fR \- Display status information for the nodes in your infrastructure
.
.SH "SYNOPSIS"
\fBknife\fR \fBstatus\fR \fI(options)\fR
.
.TP
\fB\-r\fR, \fB\-\-run\-list RUN_LIST\fR
Show the run list
.
.SH "DESCRIPTION"
The \fIstatus\fR sub\-command searches the Chef Server for all nodes and displays information about the last time the node checked into the server and executed a \fBnode\.save\fR\. The fields displayed are the relative checkin time, the node name, it\'s operating system platform and version, the fully\-qualified domain name and the default IP address\. If the \fB\-r\fR option is given, the node\'s run list will also be displayed\. Note that depending on the configuration of the nodes, the FQDN and IP displayed may not be publicly reachable\.
.
.SH "SEE ALSO"
\fBknife\-search\fR(1)
.
.SH "AUTHOR"
Chef was written by Adam Jacob \fIadam@opscode\.com\fR with many contributions from the community\.
.
.SH "DOCUMENTATION"
This manual page was written by Joshua Timberman \fIjoshua@opscode\.com\fR\. Permission is granted to copy, distribute and / or modify this document under the terms of the Apache 2\.0 License\.
.
.SH "CHEF"
Knife is distributed with Chef\. \fIhttp://wiki\.opscode\.com/display/chef/Home\fR
