name: All checks pass
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  allchecks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@204ff63e89eabdc8086f0c50b91f675bcf37c8f6 # v2
        with:
          # Retry every minute for 30 minutes...
          retries: 90
          verbose: true
