name: SonarQube scan

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
      types: [opened, synchronize, reopened]

concurrency:
  group: sonarqube-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  sonarqube:
    # this fails for all users - internal and external - with:
    # ERROR: You're not authorized to run analysis. Please contact the project administrator.
    #
    # So disabling for now until someone looks into this.
    if: ${{ false }}
    runs-on: ip-range-controlled
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@45f27363d4ff7d6b16baa0516490f10c52bdd5fc # master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
