---
name: Validate PowerShell

on:
  push:
    branches: [ chef-18 ]
  pull_request:
    branches: [ chef-18 ]

jobs:
  validate-powershell:
    runs-on: windows-2022
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Chef installation and validation in Windows Core container
        run: |
          # Run the ultra-minimal validation first to isolate encoding issues
          Write-Output "Testing with ultra-minimal script first..."
          docker run --rm -v "${PWD}:C:\workspace" -w C:\workspace mcr.microsoft.com/windows/servercore:ltsc2022 powershell -ExecutionPolicy Bypass -File "scripts\validate-powershell-ultra-minimal.ps1"
          
          # If ultra-minimal works, try the regular minimal
          Write-Output "Ultra-minimal test passed, trying regular minimal..."
          docker run --rm -v "${PWD}:C:\workspace" -w C:\workspace mcr.microsoft.com/windows/servercore:ltsc2022 powershell -ExecutionPolicy Bypass -File "scripts\validate-powershell-minimal.ps1"
          
          # If both work, run the full validation
          Write-Output "All tests passed, running full validation..."
          docker run --rm -v "${PWD}:C:\workspace" -w C:\workspace mcr.microsoft.com/windows/servercore:ltsc2022 powershell -ExecutionPolicy Bypass -File "scripts\validate-powershell.ps1"
        
      - name: Cleanup
        if: always()
        run: |
          # Clean up any test files
          if (Test-Path C:\temp\chef_test.txt) {
            Remove-Item C:\temp\chef_test.txt -Force
          }
          if (Test-Path validate_powershell.rb) {
            Remove-Item validate_powershell.rb -Force  
          }