---
name: Validate PowerShell

on:
  push:
    branches: [ chef-18 ]
  pull_request:
    branches: [ chef-18 ]

jobs:
  validate-powershell:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Chef installation and validation in Windows Core container
        run: |
          # Run the validation in a Windows Server Core container using the PowerShell script
          docker run --rm -v "${PWD}:C:\workspace" -w C:\workspace mcr.microsoft.com/windows/servercore:ltsc2022 powershell -ExecutionPolicy Bypass -File "scripts\validate-powershell.ps1"
        
      - name: Cleanup
        if: always()
        run: |
          # Clean up any test files
          if (Test-Path C:\temp\chef_test.txt) {
            Remove-Item C:\temp\chef_test.txt -Force
          }
          if (Test-Path validate_powershell.rb) {
            Remove-Item validate_powershell.rb -Force
          }
