source 'https://rubygems.org'

gemspec :name => "chef"

gem "dep_selector", :group => :server, :platform => "ruby"
gem "activesupport", "< 4.0.0", :group => :compat_testing, :platform => "ruby"

group(:docgen) do
  gem "ronn"
end

group(:development, :test) do
  gem 'rack'

  gem 'ruby-shadow', :platforms => :ruby unless RUBY_PLATFORM.downcase.match(/(darwin|freebsd)/)
#  gem 'awesome_print'
#  gem 'pry'
end

# If you want to load debugging tools into the bundle exec sandbox,
# add these additional dependencies into chef/Gemfile.local
eval(IO.read(__FILE__ + '.local'), binding) if File.exists?(__FILE__ + '.local')
